stable version refactored script run-stat-report

diff --git a/flowd/run-stat-flowd-tuple b/flowd/run-stat-flowd-tuple
--- a/flowd/run-stat-flowd-tuple
+++ b/flowd/run-stat-flowd-tuple
@@ -10,13 +10,11 @@
 #
 #	See the particular etc/*.flow file for what is OK or not OK.
 #  Usage:
-#	sbin/run-stat-flowd-tuple run/
-#	sbin/run-stat-flowd-tuple sync/root/wework/run
-#  See:
-#	#  for meaning of process states (green|yello|red) for boot
-#	#  both boot and recent statistics
-#
-#		sbin/run-stat-tuple	#  for meaning of process state
+#	sbin/run-stat-flowd-tuple flowd 
+#	sbin/run-stat-flowd-tuple flowd>wework
+#  Exit Status:
+#	0	gyr tuple written
+#	1	unexpected error, no tuple written
 #
 
 STALE_AFTER=61		#  need to derive heartbeat values in etc/profile
@@ -27,21 +25,17 @@ die()
 	exit 1
 }
 
-test $# = 2 || die "wrong number of arguments: got $#, expected 2"
+test $# = 1 || die "wrong number of arguments: got $#, expected 1"
 
 WHAT=$1		#  process name (flowd or flowd>tag)
-RUN_PATH=$2	#  run path
-
 FLOW_PATH=	#  path to *.flow file, in root or sync/peer
 
-PID_PATH=		#  path to $RUN_PATH/flowd.pid
+PID_PATH=	#  path to $RUN_PATH/flowd.pid
 PID_MTIME=null	#  most recent write to $RUN_PATH/flowd.pid
 
 BOOT_EPOCH=null	#  tail -1 $RUN_PATH/flowd.pid
-			#  can be overriden by value in "run/flowd.gyr"
+		#  can be overriden by value in "run/flowd.gyr"
 BOOT_GYR='null	null	null'
-
-GYR_PATH=$RUN_PATH/flowd.gyr
 
 RECENT_EPOCH=null	#  epoch of most recent GYR sample
 RECENT_GYR='null	null	null'
@@ -49,10 +43,17 @@ RECENT_GYR='null	null	null'
 PID_PATH=$RUN_PATH/flowd.pid
 case $WHAT in
 flowd)
-	FLOW_PATH=$RUN_PATH/etc/blobio.flow
+	GYR_PATH=run/flowd.gyr
+	PID_PATH=run/flowd.pid
+	FLOW_PATH=etc/blobio.flow
 	;;
 'flowd>'*)
-	FLOW_PATH=$RUN_PATH/etc/sync-$(echo $WHAT  | sed @/.*@@).flow
+	TAG=$(echo $WHAT  | sed 's/......//')
+	SYNC_ROOT=sync/root/$TAG/
+
+	GYR_PATH=$SYNC_ROOT/run/flowd.gyr
+	PID_PATH=$SYNC_ROOT/run/flowd.pid
+	FLOW_PATH=sync/root/$TAG/etc/sync-$TAG.flow
 	;;
 *)
 	die "_cat_flowd: impossible what: $1"
@@ -67,10 +68,14 @@ esac
 #
 if [ -e $FLOW_PATH ]; then
 	if [ -e $PID_PATH ];  then
-		if stale-mtime $STALE_AFTER $PID_PATH;  then
-			STATE=YETI
+		if [ -s $PID_PATH ];  then
+			if stale-mtime $STALE_AFTER $PID_PATH;  then
+				STATE=YETI
+			else
+				STATE=UP
+			fi
 		else
-			STATE=UP
+			STATE=YETI
 		fi
 	else
 		STATE=DOWN
@@ -84,24 +89,32 @@ else
 		STATE=ZOMBI
 	fi
 fi
+
 if [ -e $PID_PATH ];  then
 	if [ -s $PID_PATH ];  then
 		BOOT_EPOCH=$(tail -1 $PID_PATH)
 	fi
 fi
 
+#  is -s test redundant with above -s test?
 if [ -s $PID_PATH ];  then
 	PID_MTIME=$(stat-mtime $PID_PATH)
 	BOOT_EPOCH=$(tail -1 $PID_PATH)
 fi
 
-if [ -s $GYR_PATH ];  then
-	BOOT_EPOCH=$(grep '^boot	' $GYR_PATH | cut -f2)
-	BOOT_GYR=$(grep '^boot	' $GYR_PATH | cut -f3-5)
-	RECENT_EPOCH=$(grep '^recent	' $GYR_PATH | cut -f2)
-	RECENT_GYR=$(grep '^recent	' $GYR_PATH | cut -f3-5)
+if [ -e $GYT_PATH ];  then
+	if [ -s $GYR_PATH ];  then
+		BOOT_EPOCH=$(grep '^boot	' $GYR_PATH | cut -f2)
+		BOOT_GYR=$(grep '^boot	' $GYR_PATH | cut -f3-5)
+		RECENT_EPOCH=$(grep '^recent	' $GYR_PATH | cut -f2)
+		RECENT_GYR=$(grep '^recent	' $GYR_PATH | cut -f3-5)
+	elif [ $STATE = UP ];  then
+		STATE=YETI
+	fi
+elif [ $STATE = UP ];  then
+	STATE=YETI
 fi
+
 cat <<END
-$WHAT	$BOOT_EPOCH	$BOOT_GYR	$RECENT_EPOCH	$RECENT_GYR
+$WHAT	$STATE	$BOOT_EPOCH	$BOOT_GYR	$RECENT_EPOCH	$RECENT_GYR
 END
-return 0
