reset etc/* files to writable

diff --git a/dev-reboot b/dev-reboot
--- a/dev-reboot
+++ b/dev-reboot
@@ -53,6 +53,9 @@ leave()
 
 reset_etc()
 {
+	log 'reset  etc/ to writable ...'
+	find etc -type f | xargs --no-run-if-empty chmod +w
+	test "${PIPESTATUS[*]}" = '0 0'	|| die 'pre: find etc | chmod failed'
 	log 'resetting conf files in directory etc/'
 	while [ "$1" ];  do
 		F="$1"
@@ -68,7 +71,7 @@ reset_etc()
 		BF=tmp/$F.bak
 		if [ -e $EF ];  then
 			log "copy $EF -> $BF"
-			cp $EF $BF			|| die "cp $BF failed"
+			cp $EF $BF		|| die "cp $BF failed"
 		fi
 
 		LF=lib/$F.example
@@ -76,8 +79,9 @@ reset_etc()
 
 		log "copy $LF -> $EF"
 		cp $LF $EF			|| die "cp $LF $EF failed"
-		chmod +w $EF			|| die "chmod $EF failed"
 	done
+	find etc -type f | xargs --no-run-if-empty chmod +w
+	test "${PIPESTATUS[*]}" = '0 0'	|| die 'post: find etc | chmod failed'
 }
 
 case $# in
@@ -150,7 +154,6 @@ zap-proc run/bio4d.pid bio4d-listen
 
 log 'zap files in directories: run/ log/ and sync/remote'
 (
-	echo bloody-bsd-xargs-missing-no-run-if-empty
 	find run log -follow -type f					|
 		#  don't zap log/dev-reboot.log
 		fgrep -v log/dev-reboot.log
@@ -161,7 +164,10 @@ log 'zap files in directories: run/ log/ and sync/remote'
 		-type d							\
 		\( -name log -o -name run \)				\
 	     ) -type f -follow
-) | xargs rm -vf
+) | xargs --no-run-if-empty rm -vf
 
 reset_etc bash_login-dev profile psqlrc blobio.flow || exit 1
+mv etc/bash_login-dev etc/bash_login					||
+	die "mv etc/bash_login-dev failed: exit status=$?"
+
 exec cron-reboot --no-zap-flowd $@
