rewrote to use duration-human

diff --git a/run-stat-report b/run-stat-report
--- a/run-stat-report
+++ b/run-stat-report
@@ -5,49 +5,46 @@
 #  Usage:
 #	run-stat-report
 #  See:
-#	sbin/run-stat
+#	/usr/local/jmscottsbin/run-stat
 #	https://github.com/jmscott/work
+#  Exit Status:
+#	0	ok
+#	1	error
 #  Note:
-#	Calculate durations using program jmscott/work/duration-human!
-#
-#	Sort is ignoring the second key on linux.  The pain never ends.
+#	On gnu/linux sort is ignoring the second key.  The pain never ends.
 #
 #	Rename this script to run-pid-report?
 #
+NOW=$(date +'%s')
+
+die()
+{
+	echo "$(basename $0): ERROR: $@" >&2
+	exit 1
+}
+
 (
 	echo "Process	Status	Duration"
 	echo '-------------	------	-----------'
 	run-stat							|
 		sort --key=2 --key=1 --field-separator=$'\t'		|
-		awk -F'\t' -v NOW=$(date +'%s') '{
-			ELAPSED=NOW - $3;
-			DURATION="unknown";
-			units = "";
-			if ($3 ~ "^[0-9][0-9]*$") {
-
-				#  > 3 days
-				if (ELAPSED > 259200) {
-					DURATION = ELAPSED / 86400;
-					units="day";
-
-				#  > 3 hours
-
-				} else if (ELAPSED > 10800) {
-					DURATION = ELAPSED / 3600;
-					units="hr";
-
-				#  > 3 minutes
-
-				} else if (ELAPSED > 180) {
-					DURATION = ELAPSED / 60;
-					units = "min"
-				} else {
-					DURATION = ELAPSED
-					units = "sec";
-				}
-				DURATION = sprintf("%.0f", DURATION);
-			}
-
-			print $1, FS, $2, FS, DURATION, units;
-		}'
+		while read PID STATUS START_EPOCH;  do
+			DURATION_SEC=$(expr $NOW - $START_EPOCH)
+			case "$DURATION_SEC" in
+			[0-9]*)
+				;;
+			-*)
+				DURATION_SEC=0
+				;;
+			'')
+				die 'empty process duration'
+				;;
+			*)
+				die "unexpected process duration: $DURATION_SEC"
+				;;
+			esac
+			DURATION=$(duration-english $DURATION_SEC)
+			echo "$PID	$STATUS	$DURATION"
+		done
+		
 ) | column -s '	' -t | sed 's/ *	//'
