zapped mixed use of BLOBIO_SERVICE and BLOBIO_RO_SERVICE

diff --git a/cli/bio-file b/cli/bio-file
--- a/cli/bio-file
+++ b/cli/bio-file
@@ -7,8 +7,7 @@
 #	setspace@gmail.com
 #
 PROG=$(basename $0)
-SERVICE=${BLOBIO_RO_SERVICE:=$BLOBIO_SERVICE}
-ALGORITHM=sha
+ALGORITHM=${BLOBIO_ALGORITHM:=sha}
 TMP_FILE=${TMPDIR:=/tmp}/$PROG.$$
 
 die()
@@ -26,14 +25,17 @@ leave()
 
 trap leave EXIT
 
-test -n "$SERVICE" || die 'env variable not defined: BLOBIO_SERVICE'
+test -n "$BLOBIO_SERVICE" || die 'env variable not defined: BLOBIO_SERVICE'
 
 while [ "$1" ]; do
 	UDIG="$1";  shift
 
 	rm -f $TMP_FILE || die "rm -f $TMP_FILE failed: eit status=$?"
 
-	blobio get --udig $UDIG --service $SERVICE --output-path $TMP_FILE
+	blobio get 							\
+		--udig $UDIG
+		--output-path $TMP_FILE					\
+		--service $BLOBIO_SERVICE
 	STATUS=$?
 	case "$STATUS" in
 	0)
@@ -43,7 +45,7 @@ while [ "$1" ]; do
 		continue
 		;;
 	*)
-		die "blob get $UDIG $SERVICE failed"
+		die "blob get $UDIG $BLOBIO_SERVICE failed"
 		;;
 	esac
 	echo ">$UDIG	$(file --brief $TMP_FILE | sed 's/	/ /g')"
diff --git a/cli/bio-get b/cli/bio-get
--- a/cli/bio-get
+++ b/cli/bio-get
@@ -6,8 +6,7 @@
 #  	jmscott@setspace.com
 #	setspace@gmail.com
 #
-ALGORITHM=sha
-SERVICE=${BLOBIO_RO_SERVICE:=$BLOBIO_SERVICE}
+ALGORITHM=${BLOBIO_ALGORITHM:=sha}
 
 die()
 {
@@ -15,7 +14,7 @@ die()
 	exit 1
 }
 
-test -n "$SERVICE" || die 'env variable not defined: BLOBIO_SERVICE'
+test -n "$BLOBIO_SERVICE" || die 'env variable not defined: BLOBIO_SERVICE'
 
 while [ "$1" ]; do
 	case "$1" in
@@ -43,7 +42,7 @@ while [ "$1" ]; do
 	#
 	#  Fetch the file from the blob server.
 	#
-	blobio get --udig $UDIG --service $SERVICE  --output-path $FILE
+	blobio get --udig $UDIG --service $BLOBIO_SERVICE --output-path $FILE
 	STATUS=$?
 	case $STATUS in
 	0)
@@ -53,7 +52,7 @@ while [ "$1" ]; do
 		echo "?$UDIG"
 		;;
 	*)
-		die "blobio get $UDIG $SERVICE $FILE failed: status=$STATUS"
+		die "blobio get $UDIG $FILE failed: status=$STATUS"
 		;;
 	esac
 done
