stable, brute force sync

diff --git a/sync/sync-wrap-chain b/sync/sync-wrap-chain
--- a/sync/sync-wrap-chain
+++ b/sync/sync-wrap-chain
@@ -1,20 +1,27 @@
 #!/bin/bash
 #
 #  Synopsis:
-#	Efficently sync a remote blobio server from a local chain of wrap sets.
+#	Brute force sync of local blobs in a chain of wrap sets to remote.
+#  Description:
+#	Sync local blobs derived from a chain of logs of wrapped blob request
+#	requests.  The source is the local server in $BLOBIO_SERVICE.
+#	The remote server is specified on the command line.  Each blob
+#	is verified on the remote server with an "eat" request.
 #  Usage:
-#	sync-wrap-chain <local|remote> <remote host> <stop brr log count>
+#	sync-wrap-chain <remote service> <stop brr log count>
 #  Exit Status:
 #	0	no error, all blobs sunk across the chain of wrap sets.
 #	1	wrong number of arguments
 #	2	unknown error
+#  Note:
+#	Deleted blobs are not zapped.
 #
 
 PROG=$(basename $0)
 
 log()
 {
-	echo "$PROG: $@"
+	echo "$(date +'%Y/%m/%d %H:%M:%S'): $@"
 }
 
 die()
@@ -44,16 +51,13 @@ leave()
 	exit
 }
 
-test $# = 3 || die 1 "wrong number of arguments, got $#, expected 3"
+test $# = 2 || die 1 "wrong number of arguments, got $#, expected 2"
+REMOTE_SERVICE=$1
+STOP_BRR_LOG_COUNT=$2
 log 'hello, world'
 trap leave EXIT QUIT INT TERM
 
-DIRECTION=$1
-SYNC_HOST=$2
-STOP_BRR_LOG_COUNT=$3
-
-log "direction: $DIRECTION"
-log "sync host: $SYNC_HOST"
+log "remote service: $REMOTE_SERVICE"
 log "stop brr log count: $STOP_BRR_LOG_COUNT"
 
 #  Local profile in $BLOBIO_ROOT/etc/profile
@@ -63,20 +67,9 @@ cd $BLOBIO_ROOT || die "cd $BLOBIO_ROOT failed: exit status=$?"
 test -r etc/profile || die "profile does not exist: $(pwd)/etc/profile"
 . etc/profile || die "$(pwd)/etc/profile failed"
 test -n "$BLOBIO_SERVICE" || die 'environment not defined: BLOBIO_SERVICE'
+log "local blobio service: $BLOBIO_SERVICE"
 
-#  Remote profile in $BLOBIO_ROOT/sync/host/$SYNC_HOST/etc/profile
-
-SYNC_ROOT=$BLOBIO_ROOT/sync/host/$SYNC_HOST
-log "sync root: $SYNC_ROOT"
-cd $SYNC_ROOT || die "cd $SYNC_ROOT failed: exit status=$?"
-test -r etc/profile || die "sync profile does not exit: $(pwd)/etc/profile"
-. etc/profile || die "$(pwd)/etc/profile failed"
-test -n "$BLOBIO_SYNC_SSH_AUTH" ||
-			die 'environment not defined: BLOBIO_SYNC_SSH_AUTH'
-
-log "sync ssh auth: $BLOBIO_SYNC_SSH_AUTH"
-
-#  make the work dir
+#  make the temporary work dir
 
 TMPDIR=${TMPDIR:=/tmp}
 WORK_DIR=$TMPDIR/$PROG-$$.d
@@ -89,5 +82,39 @@ walk-wrap-set --stop-brr-log-count $STOP_BRR_LOG_COUNT >WALK_WRAP_SET	||
 			die "walk-wrap-set failed: exit status=$?"
 test -s WALK_WRAP_SET || die 'walk wrap set is empty'
 
+#  dump the stats of this chain of wrap set
 grep '#' WALK_WRAP_SET
-ls
+
+REMOTE_SERVICE="--service $REMOTE_SERVICE"
+SERVICE="--service $BLOBIO_SERVICE"
+log 'syncing local blobs to remote service'
+grep '^[a-z][a-z0-9].*:' WALK_WRAP_SET | while read U;  do
+	UDIG="--udig $U"
+	blobio eat $REMOTE_SERVICE $UDIG
+	STATUS=$?
+	case $STATUS in
+	0)
+		log "@$U"
+		continue
+		;;
+	1)
+		;;
+	*)
+		die "blobio eat failed: exit status=$?"
+		;;
+	esac
+
+	blobio get $SERVICE $UDIG | blobio put $REMOTE_SERVICE $UDIG
+	STATUS=${PIPESTATUS[*]}
+	case "$STATUS" in
+	'0 0')
+		log ">$U"
+		;;
+	'1 '*)
+		die "local blob does not exist: $U"
+		;;
+	*)
+		die "blobio get | put failed: exit status=$STATUS"
+		;;
+	esac
+done
