created zap-proc for all your pkill needs

diff --git a/biod/biod_ctl b/biod/biod_ctl
--- a/biod/biod_ctl
+++ b/biod/biod_ctl
@@ -27,42 +27,6 @@ WARN()
 	log "WARN: $@"
 }
 
-_pkill()
-{
-	log "pkill $@ ..."
-	case "$1" in
-	[0-9]*)
-		log "kill $@ ..."
-		kill $1
-		;;
-	*)
-		log "pkill $@ ..."
-		pkill $@
-		;;
-	esac
-	STATUS=$?
-	case $STATUS in
-	0)
-		log "killed an existing biod process tree"
-		log "pausing $PAUSE secs while biod cleans up ..."
-		sleep $PAUSE
-		test -e $PID && die "pid file exists after kill: $PID"
-		;;
-	1)
-		log 'no biod process exists'
-		if [ -f $PID ];  then
-			WARN "zapping existing pid file: $PID"
-			chmod +w $PID
-			test $? -eq 0 || die "chmod $PID failed: exit status=$?"
-			rm $PID || die "rm $PID failed: exit status=$?"
-		fi
-		;;
-	*)
-		die "pkill $@ failed: exit status=$STATUS"
-		;;
-	esac
-}
-
 ACTION="$1"
 case "$BLOBIO_ROOT" in
 '')
@@ -89,9 +53,10 @@ boot)
 	rm -f $PID
 	;;
 start)
-	if [ -f $PID ];  then
-		log "is biod already running with pid #$(cat $PID)?" >&2
-		die "remove file: $PID"
+	PID_FILE=run/biod.pid
+	if [ -f $PID_FILE ];  then
+		log "is biod already running with pid #$(cat $PID_FILE)?" >&2
+		die "remove file: $PID_FILE"
 	fi
 	$BIOD --ps-title-XXXXXXXXXXXXXXXXXXXXXXX --port $PORT		\
 				--rrd-sample-duration $RRD_SAMPLE_DURATION
@@ -100,59 +65,16 @@ start)
 
 	log "pausing $PAUSE seconds while biod starts ..."
 	sleep $PAUSE
-	test -f $PID || die "missing pid file $PID, so did biod aborted"
-	log "started with pid #$(cat $PID)"
+	test -f $PID_FILE || die "no pid file $PID_FILE, so biod aborted"
+	log "started with pid #$(cat $PID_FILE)"
 	log 'tail of log file follows ...'
 	tail log/biod-$(date +'%a').log
 	;;
 stop)
-	if [ -e $PID ];  then
-		P=$(cat $PID)
-		log "stopping biod #$P ..."
-		kill $P
-		log "pausing $PAUSE seconds while biod #$P stops ..."
-		sleep $PAUSE
-		if [ -f $PID ];  then
-			WARN "biod #$P still running"
-			WARN "kill -9 #$P"
-			kill -9 $P
-		fi
-		log '... biod stopped'
-	else
-		log "biod not running since no pid file: $PID"
-	fi
+	zap-proc run/biod.pid
 	;;
 reboot)
-	if [ -e $PID ];  then
-		log "pid file exists: $PID"
-		P=$(cat $PID)
-		log "killing process #$P"
-		_pkill $P
-	fi
-	#
-	#  Zap biod that lost pid file.
-	#
-	#  Note:
-	#	Need a better qualification on which biod process to kill.
-	#	Implies only a single biod per user, which is hosed
-	#	in development
-	#
-	pgrep -o -u $USER -x biod
-
-	STATUS=$?
-	case $STATUS in
-	0)
-		WARN 'biod process exists with no pid file'
-		WARN 'killing oldest biod process'
-		_pkill -o -u $USER -x biod
-		;;
-	1)
-		log 'no running biod process'
-		;;
-	*)
-		die "pgrep biod failed: exit status=$STATUS"
-		;;
-	esac
+	zap-proc run/biod.pid
 	biod_ctl start
 	;;
 restart)
diff --git a/biod/reboot-sync b/biod/reboot-sync
--- a/biod/reboot-sync
+++ b/biod/reboot-sync
@@ -10,6 +10,7 @@
 #	#  From cron-reboot
 #	reboot-sync
 #
+PKILL_USER=$(id -un)
 
 log()
 {
@@ -34,47 +35,28 @@ if [ ! -e sync/host ];  then
 	mkdir -p sync/host || die "mkdir failed: $(pwd)/sync/host"
 fi
 
+logh()
+{
+	log "$HOST: $@"
+}
+
+dieh()
+{
+	die "$HOST: $@"
+}
+
 find $BLOBIO_ROOT/sync/host/ -mindepth 1 -maxdepth 1 -type d 		|
   while read SYNC_ROOT;  do
 	HOST=$(basename $SYNC_ROOT)
 	log "sync host: $HOST"
-	cd $SYNC_ROOT || die "cd $SYNC_ROOT failed: exit status=$?"
+	cd $SYNC_ROOT || dieh "cd $SYNC_ROOT failed: exit status=$?"
 
-	#  stop any running processes
-	if [ -e run/flowd.pid ];  then
-		log 'file run/flowd.pid exists'
-		PID=$(cat run/flowd.pid)
-		log "killing flowd process possibly owned by $USER: #$PID"
-		pkill -F run/flowd.pid -U $USER flowd
-		STATUS=$?
-		case "$STATUS" in
-		0)
-			log "zapped flowd process with pid #$PID"
-			log "sleeping 3 seconds will flowd (#$PID) exits ..."
-			sleep 3
-			;;
-		1)
-			log "no process matches with pid #$PID"
-			rm run/flowd.pid ||
-				die "rm run/flowd.pid failed: exit status=$?"
-			;;
-		*)
-			die "pkill failed; exit status=$?"
-			;;
-		esac
-
-		#  make sure run/flowd.pid got removed by clean exit.
-		#  otherwise, nuke flowd process with SIGKILL.
-
-		if [ -e run/flowd.pid ];  then
-			log 'ERROR: run/flowd.pid still exists'
-			log "killing #$PID with SIGKILL"
-			kill -9 $PID
-			rm -f run/flowd.pid ||
-				die "rm run/flowd.pid failed: exit status=$?"
-		fi
-	fi
+	zap-proc run/flowd.pid || dieh "zap-proc flowd failed: exit status=$?"
 	log "starting sync flowd server: $HOST ..."
 	log "BLOBIO_ROOT for sync flowd: $SYNC_ROOT"
 	BLOBIO_ROOT=$SYNC_ROOT flowd server etc/sync-$HOST.flow &
+	FLOWD_PID=$!
+	log "flowd process id: $FLOWD_PID"
+	echo $FLOWD_PID >run/flowd.pid ||
+		die "echo $FLOWD_PID >run/flowd.pid failed: exit status=$?"
 done
diff --git a/cron-reboot b/cron-reboot
--- a/cron-reboot
+++ b/cron-reboot
@@ -9,6 +9,7 @@
 #
 
 PROG=$(basename $0)
+USER=$(id -un)
 
 log()
 {
@@ -35,52 +36,7 @@ log "BLOBIO_ROOT=$BLOBIO_ROOT"
 cd $BLOBIO_ROOT || die "cd $BLOBIO_ROOT failed"
 . etc/profile
 
-#
-#  Stop any running flowd process using pkill/pgrep brothers
-#
-PGREP_RE='flowd server etc/blobio.flow'
-log "pkill $PGREP_ARGV ..."
-
-pkill -u $USER -f "$PGREP_RE"
-STATUS=$?
-case $STATUS in
-0)
-	log 'flowd was running and killed'
-	;;
-1)
-	log 'no flowd process found'
-	;;
-*)
-	die "PANIC: pkill $USER flowd failed: exit status=$STATUS"
-	;;
-esac
-
-#
-#  Insure flowd has stopped
-#
-if [ $STATUS = 0 ];  then
-	TRIES=10
-	PAUSE=2
-	log "pausing $PAUSE seconds while flowd exits"
-	while sleep $PAUSE;  do
-		test $TRIES -eq 0 && die "can't kill flowd"
-		pgrep -u $USER -f "$PGREP_RE" >/dev/null
-		STATUS=$?
-		case $STATUS in
-		0)
-			log "flowd stilling running: remaining attempts: $TRIES"
-			;;
-		1)
-			log 'flowd not running'
-			break
-			;;
-		*)
-			die "pgrep $PGREP_ARGV failed: exit status=$STATUS"
-			;;
-		esac
-		TRIES=$(expr $TRIES - 1)
-	done
-fi
+zap-proc run/flowd.pid || die "zap-proc flowd failed: exit status=$?"
 
 log 'calling biod_ctl reboot ...'
 biod_ctl reboot
@@ -89,6 +45,9 @@ log 'biod_ctl reboot ok'
 
 log 'starting flowd server in background ...'
 flowd server etc/blobio.flow &
-log "flowd server process id is $!"
+FLOWD_PID=$!
+log "flowd server process id is $FLOWD_PID"
+echo $FLOWD_PID >run/flowd.pid ||
+		die "echo $FLOWD_PID >run/flowd.pid failed: exit status=$?"
 
 exit 0
