replaced file-stat-size with GNU stat

diff --git a/bio4d/fs-frisk b/bio4d/fs-frisk
--- a/bio4d/fs-frisk
+++ b/bio4d/fs-frisk
@@ -14,6 +14,14 @@
 #	corrupted has highest priority, then missing, then no errors.
 #	so, if bad_count > 0 then exit 2;  if missing_count > 0 then exit 1;
 #  Note:
+#	Tracking empty bad blobs would be nice.
+#
+#	Consider script fs-frisk-size, which consults pg table blobio.service.
+#
+#	zero data blocks when corrupted, so an fs-frisk-empty would scan much
+#	more quicklu
+#	Consider script of option to frisk a limited set of udigs.
+#
 #	Need to insure bot WORK_DIR and $BLOBIO_ROOT/data/fs_*
 #	are on the same file systems.
 #
@@ -58,7 +66,7 @@ log "TMPDIR=$TMPDIR"
 log "work dir: $WORK_DIR"
 mkdir "$WORK_DIR" || die "mkdir work dir failed: exit status=$?"
 
-cd $WORK_DIR || die "cd work dir failed: exist status=$?"
+cd $WORK_DIR || die "cd work dir failed: exit status=$?"
 DATA=$BLOBIO_ROOT/data
 log "data dir: $DATA"
 test -d $DATA || die "cannot verify blob data dir: $DATA"
@@ -79,6 +87,7 @@ let progress_mod=0
 let ok_count=0
 let bad_count=0
 let missing_count=0
+let byte_total=0		#  range is [0-2^63), even on 32bit pi
 
 while read U P;  do
 	let progress=count%PROGRESS_MODULUS
@@ -94,7 +103,7 @@ while read U P;  do
 	'')
 		ERROR $ALGO
 		ERROR "empty extracted algo: $U"
-		log "!$U"
+		ERROR "!$U"
 		continue
 		;;
 	*)
@@ -107,10 +116,11 @@ while read U P;  do
 
 	BP=$BLOBIO_ROOT/data/$P
 
-	#  minor race condition until "blobio eat" has specific
-	#  exit status for missing --input-path.
+	#  minor race condition if blob is taken after successfull eat.
+
 	if [ ! -e $BP ];  then
-		log "?$U"
+		ERROR 'possible race, blob file disappeared after ok blob eat'
+		ERROR "?$U"
 		let missing_count+=1
 		continue
 	fi
@@ -118,16 +128,25 @@ while read U P;  do
 	STATUS=$?
 	case $STATUS in
 	0)
-		if [ "$ALGO:$D" = $U ];  then
-			let ok_count+=1
-		else
+		if [ "$ALGO:$D" != $U ];  then
 			if [ "$D" = '' ];  then
 				ERROR 'eat: empty digest'
 			else
 				ERROR "eat: unexpected algo:digest: $ALGO:$D"
 			fi
-			log "!$U"
+			ERROR "!$U"
 			let bad_count+=1
+			continue
+		fi
+
+		let ok_count+=1
+		SZ=$(stat --format '%s' $BP)
+		STATUS=$?
+		if [ $STATUS = 0 ];  then
+			let byte_total+=$SZ
+		else
+			ERROR "file-stat-size failed: exit status"
+			ERROR "!$U"
 		fi
 		;;
 	*)
@@ -139,6 +158,7 @@ log "ok count: $ok_count"
 log "missing count: $missing_count"
 log "bad count: $bad_count"
 log "scanned: $count blobs total"
+log "byte total: $byte_total bytes"
 
 if (($bad_count>0));  then
 	if (($missing_count>0)); then
