pgrep verify running process

diff --git a/bio4d/run-stat-bio4d-tuple b/bio4d/run-stat-bio4d-tuple
--- a/bio4d/run-stat-bio4d-tuple
+++ b/bio4d/run-stat-bio4d-tuple
@@ -45,6 +45,18 @@ RECENT_GYR='null	null	null'
 if [ -e $PID_PATH ];  then
 	STATE=UP
 	if [ -s $PID_PATH ];  then
+		pgrep -F $PID_PATH
+		STATUS=$?
+		case $STATUS in
+		0)
+			;;
+		1)
+			STATE=YETI
+			;;
+		*)
+			die "pgrep failed: exit status=$STATUS"
+			;;
+		esac
 		BOOT_EPOCH=$(tail -1 $PID_PATH)
 	else
 		STATE=YETI
