added transaction log spool/cron-rummy.txn

diff --git a/pgsql/cron-rummy b/pgsql/cron-rummy
--- a/pgsql/cron-rummy
+++ b/pgsql/cron-rummy
@@ -1,14 +1,23 @@
 #!/bin/bash
 #
 #  Synopsis:
-#	Find blobs in service with missing information.
+#	Find blobs in pg service table with missing information, back to PIT.
 #  Usage:
-#	*/15 * * * *	cron-rummy '-1week' >>log/cron-rummy.log 2>&1
-#  Note:
-#	Move to $BLOBIO_ROOT/sbin
+#	export BLOBIO_ROOT=/opt/jmscott/jmsdesk/blobio
+#	LOG=$BLOBIO_ROOT/log/cron-rummy.log
+#	*/15 * * * * $BLOBIO_ROOT/sbin/cron-rummy '-1week' >>$LOG
+#  Depends:
+#	https://github.com/jmscott/work
+#  Exit Status:
+#	0	ok
+#	1	error
 #
 
+START_TIME=$(RFC3339Nano)
+START_EPOCH=$(date +'%s')
+
 RUMMY_UDIG_SET=${TMPDIR:=/tmp}/$(basename $0)-$$.udig
+#  store stats for txn log, since 
 PSQL='psql --quiet --no-align --no-psqlrc --tuples-only'
 
 log()
@@ -25,7 +34,9 @@ die()
 leave()
 {
 	rm -f $RUMMY_UDIG_SET || log "ERROR: rm -f $RUMMY_UDIG_SET failed" >&2
-	log 'good bye, cruel world'
+	log "good bye, cruel world: elapsed $(
+		duration-english $(expr $(date +'%s') - $START_EPOCH)
+	)"
 }
 
 test $# = 1 || die 'wrong number of arguments'
@@ -41,6 +52,16 @@ cd $BLOBIO_ROOT || die "cd $BLOBIO_ROOT failed: exit status=$?"
 . etc/profile
 
 log "since: $SINCE"
+SINCE_SEC=$($PSQL -c "SELECT extract(epoch from '$SINCE'::interval);")
+STATUS=$?
+case "$SINCE_SEC" in
+-[1-9]*)
+	log "since seconds: $SINCE_SEC"
+	;;
+*)
+	die "psql since failed: exit status=$STATUS"
+	;;
+esac
 log "tmp rummy udig set: $RUMMY_UDIG_SET"
 log "BLOBIO_SERVICE=$BLOBIO_SERVICE"
 log "PGHOST=$PGHOST"
@@ -49,7 +70,7 @@ log "PGUSER=$PGUSER"
 log "PGPASSWORD=$PGPASSWORD"
 log "PGDATABASE=$PGDATABASE"
 
-log "service blobs not in table brr_blob_size since $SINCE"
+log "blobs not in table brr_blob_size since $SINCE"
 $PSQL --set since="$SINCE" --file=lib/cron-rummy.sql >$RUMMY_UDIG_SET	||
 	die "psql rummy failed: exit status=$?"
 
@@ -58,14 +79,21 @@ log "blobs with no brr_blob_size: $NO_SIZE_COUNT"
 
 #  fetch each blob to trigger merge of row in table brr_blob_size
 
+OK=0
+NO=0
 while read UDIG;  do
-	blobio get --udig $UDIG --service $BLOBIO_SERVICE --output-path /dev/null
+	blobio get							\
+		--udig $UDIG						\
+		--service $BLOBIO_SERVICE				\
+		--output-path /dev/null
 	STATUS=$?
 	case $STATUS in
 	0)
 		log ">$UDIG"
+		OK=$(($OK + 1))
 		;;
 	1)
+		NO=$(($NO + 1))
 		log "?$UDIG"
 		;;
 	*)
@@ -73,3 +101,10 @@ while read UDIG;  do
 		;;
 	esac
 done <$RUMMY_UDIG_SET
+
+TXN=spool/cron-rummy.txn
+log "transaction log: $TXN"
+echo "$START_TIME	$(RFC3339Nano)	$SINCE_SEC	$OK	$NO" >>$TXN ||
+	die "echo >txn failed: exit status=$?"
+
+exit 0
