renamed rrd to stat, simplified launchd-bio4d

diff --git a/pgsql/cron-bio4d-stat2pg b/pgsql/cron-bio4d-stat2pg
--- a/pgsql/cron-bio4d-stat2pg
+++ b/pgsql/cron-bio4d-stat2pg
@@ -1,23 +1,23 @@
 #!/bin/bash
 #
 #  Synopsis:
-#	Push rrd samples into the table blobio.bio4d_request_stat
+#	Push bio4d stat samples into the table blobio.bio4d_stat
 #  Note:
 #	Race condition exists between the time the log file is renamed
 #	and the insert into the database.  A slightly safer algorithm
 #	would be to sha the frozen log file before and after the put to the db.
 #
-#		FROZEN=bio4d-rrd-<timestamp>.log
-#		mv bio4d-rrd.log $FROZEN
+#		FROZEN=bio4d-stat-<timestamp>.log
+#		mv bio4d-stat.log $FROZEN
 #		sleep FLUSH_PAUSE
 #		SHA1=$(blobio eat $FROZEN)
-#		psql <bio4d-rrd-<timestamp>.log
+#		psql <bio4d-stat-<timestamp>.log
 #		SHA2=$(blobio eat $FROZEN)
 #		test $SHA1 = $SHA2 || die
 #
 
-RRD=log/bio4d-rrd.log
-FLUSH_PAUSE=${BLOBIO_RRD_FLUSH_PAUSE:=5}
+STAT=log/bio4d-stat.log
+FLUSH_PAUSE=${BLOBIO_STAT_FLUSH_PAUSE:=5}
 MERGE_SQL=lib/merge-bio4d_request_stat.sql
 PSQL='psql --no-psqlrc'
 
@@ -63,11 +63,11 @@ log "PGUSER=$PGUSER"
 log "PGPASSWORD=$PGPASSWORD"
 log "PGDATABASE=$PGDATABASE"
 
-if [ ! -e $RRD ];  then
-	log "WARN: file does not exist: $RRD"
+if [ ! -e $STAT ];  then
+	log "WARN: file does not exist: $STAT"
 	exit 1
 fi
-if [ ! -s $RRD ];  then
+if [ ! -s $STAT ];  then
 	log "WARN: file is empty: $RDD"
 	exit 2
 fi
@@ -75,16 +75,16 @@ fi
 #  move the sample file to a frozen version
 
 NOW=$(date +'%Y%m%d_%H%M%S')
-RRD_FROZEN=$(echo $RRD | sed "s/\.log$/-$NOW.log/")
-log "frozen sample file: $RRD_FROZEN"
-mv $RRD $RRD_FROZEN || die "mv $RRD $RRD_FROZEN failed"
+STAT_FROZEN=$(echo $STAT | sed "s/\.log$/-$NOW.log/")
+log "frozen sample file: $STAT_FROZEN"
+mv $STAT $STAT_FROZEN || die "mv $STAT $STAT_FROZEN failed"
 
 log "flush pause $FLUSH_PAUSE sec ..."
 sleep $FLUSH_PAUSE
 
 log "merging new samples with sql $MERGE_SQL"
-$PSQL --file $MERGE_SQL <$RRD_FROZEN || die "psql $MERGE_SQL failed: status=$?"
+$PSQL --file $MERGE_SQL <$STAT_FROZEN || die "psql $MERGE_SQL failed: status=$?"
 
-log "blobify frozen samples: $RRD_FROZEN"
-bio-put-file $RRD_FROZEN || die "bio-put-file $RRD_FROZEN failed: status=$?"
-bio-give $RRD_FROZEN || die "bio-give $RRD_FROZEN failed: status=$?"
+log "blobify frozen samples: $STAT_FROZEN"
+bio-put-file $STAT_FROZEN || die "bio-put-file $STAT_FROZEN failed: status=$?"
+bio-give $STAT_FROZEN || die "bio-give $STAT_FROZEN failed: status=$?"
